import { WordWithDefinition } from "../types";

// A comprehensive list of English Islamic-themed words for the game.
// This list enables fully offline gameplay in English.
export const en_words: WordWithDefinition[] = [
    // 4 Letters
    { word: "ADAM", definition: "The first man and the first prophet in Islam." },
    { word: "ADIL", definition: "Just, fair; one of the attributes of Allah." },
    { word: "AMAN", definition: "Safety, security, peace." },
    { word: "AMIN", definition: "Amen; a word said at the end of a prayer to mean 'O Allah, accept'." },
    { word: "ASR", definition: "The afternoon prayer; also means 'era' or 'time'." },
    { word: "AYAH", definition: "A verse of the Qur'an; also means 'sign' or 'miracle'." },
    { word: "CALM", definition: "A state of peace and tranquility." },
    { word: "DATE", definition: "A sweet fruit often eaten to break the fast in Ramadan." },
    { word: "DAWA", definition: "The act of inviting others to Islam." },
    { word: "DEED", definition: "An action or an act performed by a person." },
    { word: "DEEN", definition: "Religion or way of life, referring to Islam." },
    { word: "DOVE", definition: "A bird often symbolizing peace." },
    { word: "DUAA", definition: "Supplication, the act of asking Allah for something." },
    { word: "EDEN", definition: "A paradise or a delightful place, often referring to Jannah." },
    { word: "FAJR", definition: "The dawn prayer, performed before sunrise." },
    { word: "FARD", definition: "An obligatory act in Islam, such as the five daily prayers." },
    { word: "FAST", definition: "Abstaining from food, drink, and other physical needs during daylight hours, especially in Ramadan." },
    { word: "FATE", definition: "Predestination, the divine will and decree of Allah (Qadar)." },
    { word: "FEAR", definition: "Awe and reverence for Allah (Taqwa)." },
    { word: "FIQH", definition: "Islamic jurisprudence, the human understanding of the Sharia." },
    { word: "FOOD", definition: "Sustenance provided by Allah." },
    { word: "GIFT", definition: "A blessing or provision from Allah." },
    { word: "GIVE", definition: "To offer charity (Sadaqah) or help to others." },
    { word: "GOAL", definition: "The ultimate purpose of a Muslim's life, to worship Allah." },
    { word: "GOOD", definition: "Actions that are righteous and pleasing to Allah." },
    { word: "HAJJ", definition: "The annual Islamic pilgrimage to Mecca, a mandatory religious duty for Muslims." },
    { word: "HALA", definition: "Permissible or lawful in Islam." },
    { word: "HAQQ", definition: "The truth, reality, righteousness; one of the names of Allah." },
    { word: "HEAL", definition: "To cure or make well, a power that ultimately comes from Allah." },
    { word: "HEED", definition: "To pay attention to Allah's commands." },
    { word: "HEIR", definition: "One who inherits property according to Islamic law." },
    { word: "HELP", definition: "Assistance sought from Allah or given to others." },
    { word: "HIJR", definition: "Migration, specifically the Prophet Muhammad's migration from Mecca to Medina." },
    { word: "HOPE", definition: "Trust and reliance on Allah's mercy and forgiveness." },
    { word: "HOUR", definition: "The Day of Judgment, the final hour." },
    { word: "HURI", definition: "Companions in Paradise, often described as beautiful maidens." },
    { word: "ILM", definition: "Knowledge, particularly religious knowledge." },
    { word: "IMAM", definition: "A leader, especially one who leads the congregational prayer." },
    { word: "IMAN", definition: "Faith, belief in the articles of faith in Islam." },
    { word: "ISA", definition: "Jesus, a prophet in Islam." },
    { word: "JINN", definition: "Supernatural beings created from smokeless fire." },
    { word: "KAAB", definition: "The Kaaba, the cubic building at the center of the Grand Mosque in Mecca." },
    { word: "KIND", definition: "To be gentle and compassionate, a key Islamic virtue." },
    { word: "LAIL", definition: "Night, as in 'Lailat al-Qadr', the Night of Power." },
    { word: "LIFE", definition: "The period of existence on Earth, seen as a test for the hereafter." },
    { word: "LOVE", definition: "Affection for Allah, the Prophet, and fellow believers." },
    { word: "LUT", definition: "Lot, a prophet in Islam." },
    { word: "MARY", definition: "Maryam, the mother of Jesus (Isa), a revered figure in Islam." },
    { word: "MEAL", definition: "Food eaten at a particular time, such as Iftar or Suhoor." },
    { word: "MINA", definition: "A valley near Mecca where pilgrims perform certain Hajj rituals." },
    { word: "MOON", definition: "Used to determine the beginning and end of Islamic months." },
    { word: "MUSA", definition: "Moses, a major prophet in Islam to whom the Torah was revealed." },
    { word: "NABI", definition: "A prophet who receives revelation from Allah but is not given a new set of laws." },
    { word: "NAFS", definition: "The self, soul, or ego." },
    { word: "NOAH", definition: "Nuh, a prophet in Islam who built an ark to save believers from a great flood." },
    { word: "NOOR", definition: "Light, divine light or guidance." },
    { word: "OATH", definition: "A solemn promise, often made in the name of Allah." },
    { word: "OMAR", definition: "Umar ibn al-Khattab, the second Caliph of Islam." },
    { word: "PALM", definition: "A tree whose dates are a significant food, especially during Ramadan." },
    { word: "PATH", definition: "The straight path (Sirat al-Mustaqim), the way of Islam." },
    { word: "PRAY", definition: "To perform Salah, the ritual prayer in Islam." },
    { word: "PURE", definition: "To be in a state of ritual purity (Tahara)." },
    { word: "QADR", definition: "Divine decree, predestination." },
    { word: "RAMI", definition: "The ritual of stoning the devil performed during Hajj." },
    { word: "READ", definition: "The first command revealed in the Qur'an ('Iqra')." },
    { word: "RIBA", definition: "Usury or interest, which is forbidden in Islam." },
    { word: "RUH", definition: "The spirit or soul." },
    { word: "RULE", definition: "To govern according to Islamic principles." },
    { word: "SAFA", definition: "A hill near the Kaaba, part of the Sa'i ritual during Hajj and Umrah." },
    { word: "SAFE", definition: "To be in a state of security and peace." },
    { word: "SAWM", definition: "Fasting, one of the Five Pillars of Islam." },
    { word: "SEEK", definition: "To search for knowledge or Allah's forgiveness." },
    { word: "SHIA", definition: "A major branch of Islam that holds that the Prophet Muhammad designated Ali ibn Abi Talib as his successor." },
    { word: "SOUL", definition: "The spiritual or immaterial part of a human being (Ruh)." },
    { word: "STAR", definition: "A celestial body, mentioned in the Qur'an as signs of Allah's creation." },
    { word: "SUFI", definition: "A follower of Islamic mysticism, or Sufism." },
    { word: "SURA", definition: "A chapter of the Qur'an." },
    { word: "TAWF", definition: "Tawaf, the ritual of circumambulating the Kaaba seven times." },
    { word: "TEST", definition: "A trial or tribulation from Allah to test one's faith." },
    { word: "TRUE", definition: "In accordance with fact or reality; a characteristic of Islam." },
    { word: "TUR", definition: "Mount Sinai, where Moses received the Torah." },
    { word: "UMMA", definition: "The worldwide community of Muslims." },
    { word: "UTHM", definition: "Uthman ibn Affan, the third Caliph of Islam." },
    { word: "VEIL", definition: "A garment that covers the head and chest, such as a Hijab." },
    { word: "WAHY", definition: "Divine revelation given by Allah to His prophets." },
    { word: "WIRD", definition: "A set of prayers or supplications recited regularly." },
    { word: "WISE", definition: "Having or showing experience, knowledge, and good judgment; an attribute related to Allah's wisdom." },
    { word: "WOMB", definition: "The organ in the lower body of a woman or female mammal where offspring are conceived and in which they gestate before birth; mentioned in the context of kinship and creation." },
    { word: "WORD", definition: "The Word of Allah, referring to the Qur'an." },
    { word: "WUDU", definition: "Ritual ablution, washing parts of the body before prayer." },
    { word: "ZABI", definition: "Zabihah, the prescribed method of ritual slaughter of animals in Islam." },
    { word: "ZIKR", definition: "Dhikr, the remembrance of Allah, often through recitation of His names." },

    // 5 Letters
    { word: "AARAF", definition: "A'raf, a place between Paradise and Hell." },
    { word: "ABBAS", definition: "An uncle of the Prophet Muhammad." },
    { word: "ABDUL", definition: "Servant of, a common prefix in Islamic names (e.g., Abdullah, servant of Allah)." },
    { word: "ADAB", definition: "Manners, etiquette, and refinement in Islam." },
    { word: "ADHAN", definition: "The Islamic call to prayer." },
    { word: "AHAD", definition: "One, The One; referring to the oneness of Allah (Tawhid)." },
    { word: "AKBAR", definition: "The Greatest, as in 'Allahu Akbar' (Allah is the Greatest)." },
    { word: "ALLAH", definition: "The Arabic name for the one and only God in Islam." },
    { word: "ANGEL", definition: "A spiritual being created from light, who serves Allah (Mala'ikah)." },
    { word: "ANSAR", definition: "The helpers; the Muslims of Medina who helped the Muslims of Mecca after the Hijra." },
    { word: "AQIDA", definition: "Creed, the fundamental beliefs of Islam." },
    { word: "AQSA", definition: "Al-Aqsa Mosque in Jerusalem, the third holiest site in Islam." },
    { word: "ARABS", definition: "The people among whom Islam was first revealed." },
    { word: "ASMA", definition: "Names, as in 'Asma-ul-Husna' (the most beautiful names of Allah)." },
    { word: "AWRAH", definition: "The parts of the body that should be covered in Islam." },
    { word: "AYATS", definition: "Verses of the Qur'an." },
    { word: "BADR", definition: "The site of a famous battle in early Islamic history." },
    { word: "BARAK", definition: "Blessing, divine grace." },
    { word: "BASIR", definition: "The All-Seeing, one of the names of Allah." },
    { word: "BATIN", definition: "The Hidden, The Unmanifest; one of the names of Allah." },
    { word: "BILAL", definition: "A companion of the Prophet Muhammad, known for being the first muezzin." },
    { word: "BLESS", definition: "To confer divine favor upon; to ask for Allah's blessing." },
    { word: "BURAQ", definition: "The celestial creature that carried the Prophet Muhammad during his Night Journey (Isra and Mi'raj)." },
    { word: "DAWAH", definition: "The act of inviting others to Islam." },
    { word: "DEEDS", definition: "Actions, which are judged by Allah." },
    { word: "DHIKR", definition: "The remembrance of Allah." },
    { word: "DINAR", definition: "A type of gold coin used in early Islamic times." },
    { word: "DREAM", definition: "Visions during sleep, some of which can be a form of divine inspiration." },
    { word: "DUAAS", definition: "Supplications, prayers of request." },
    { word: "EID", definition: "A religious festival, such as Eid al-Fitr and Eid al-Adha." },
    { word: "FATIH", definition: "The opener, the conqueror; referring to the opening chapter of the Qur'an." },
    { word: "FATWA", definition: "A legal ruling on a point of Islamic law given by a qualified jurist." },
    { word: "GHAIB", definition: "The unseen, that which is beyond human perception." },
    { word: "GHUSL", definition: "Full ritual ablution, the washing of the entire body." },
    { word: "GRACE", definition: "Divine mercy and favor from Allah." },
    { word: "HADIS", definition: "A single report or narration of the Prophet Muhammad's sayings or actions." },
    { word: "HAFIZ", definition: "One who has memorized the entire Qur'an." },
    { word: "HAJAR", definition: "Hagar, the wife of Abraham and mother of Ishmael." },
    { word: "HALAL", definition: "Permissible or lawful according to Islamic law." },
    { word: "HARAM", definition: "Forbidden or unlawful according to Islamic law." },
    { word: "HIJAB", definition: "The veil or headscarf worn by Muslim women." },
    { word: "HIJRA", definition: "The migration of the Prophet Muhammad from Mecca to Medina." },
    { word: "HIJRI", definition: "The Islamic lunar calendar, which begins with the Hijra." },
    { word: "HIKMA", definition: "Wisdom, the ability to judge correctly and follow the best course of action." },
    { word: "HUDUD", definition: "Punishments for serious crimes as prescribed in the Qur'an and Sunnah." },
    { word: "IBLIS", definition: "The personal name of the Devil or Satan in Islam." },
    { word: "IHSAN", definition: "Perfection in worship, worshipping Allah as if you see Him." },
    { word: "IJMAA", definition: "Consensus, the agreement of Islamic scholars on a point of law." },
    { word: "IKRAM", definition: "Generosity, hospitality, honoring others." },
    { word: "ILAHI", definition: "Divine, related to God." },
    { word: "ILYAS", definition: "Elijah, a prophet in Islam." },
    { word: "IMAMA", definition: "The leadership of the Muslim community." },
    { word: "INJIL", definition: "The Gospel, the holy book revealed to Jesus (Isa)." },
    { word: "ISHAQ", definition: "Isaac, a prophet and the son of Abraham." },
    { word: "ISLAM", definition: "Submission to the will of Allah; the religion of Muslims." },
    { word: "ISRA", definition: "The first part of the Prophet Muhammad's Night Journey, from Mecca to Jerusalem." },
    { word: "JABIR", definition: "A well-known companion of the Prophet Muhammad." },
    { word: "JANNA", definition: "Paradise, the eternal garden of reward for the righteous." },
    { word: "JIHAD", definition: "Struggle or striving, especially in the path of Allah." },
    { word: "JUMMA", definition: "Friday, the day of congregational prayer for Muslims." },
    { word: "KABAH", definition: "The Kaaba, the sacred building in Mecca." },
    { word: "KABIR", definition: "The Great, one of the names of Allah." },
    { word: "KAFIR", definition: "A disbeliever, one who rejects the truth of Islam." },
    { word: "KALAM", definition: "Speech, word; often refers to Islamic theology." },
    { word: "KARIM", definition: "Generous, noble; one of the names of Allah." },
    { word: "KHAYR", definition: "Goodness, خير." },
    { word: "KISWA", definition: "The black silk cloth that covers the Kaaba." },
    { word: "KITAB", definition: "Book, scripture; often refers to the Qur'an." },
    { word: "LAWHI", definition: "The Preserved Tablet (al-Lawh al-Mahfuz), where all is written." },
    { word: "LAYLA", definition: "Night, as in 'Laylat al-Qadr'." },
    { word: "MAHDI", definition: "The guided one, a messianic figure who is believed to appear at the end of times." },
    // FIX: Corrected a typo in the word list.
    { word: "MAKKA", definition: "Mecca, the holiest city in Islam." },
    { word: "MALAK", definition: "Angel." },
    { word: "MALIK", definition: "King, Sovereign; one of the names of Allah; also the name of an angel who is the guardian of Hell." },
    { word: "MANAT", definition: "A pre-Islamic Arabian goddess." },
    { word: "MARUT", definition: "An angel mentioned in the Qur'an, sent to test mankind." },
    { word: "MARWA", definition: "A hill near the Kaaba, part of the Sa'i ritual." },
    { word: "MASIH", definition: "The Messiah, a title for Jesus (Isa)." },
    { word: "MECCA", definition: "The holiest city for Muslims, located in modern-day Saudi Arabia." },
    { word: "MEDINA", definition: "The second holiest city in Islam, where the Prophet Muhammad is buried." },
    { word: "MIKAL", definition: "Michael, one of the archangels in Islam." },
    { word: "MINAR", definition: "A minaret, the tower of a mosque from which the call to prayer is made." },
    { word: "MISWK", definition: "A miswak, a teeth-cleaning twig." },
    { word: "MOSES", definition: "Musa, a major prophet in Islam." },
    { word: "MOSQUE", definition: "A place of worship for Muslims." },
    { word: "MUFTI", definition: "An Islamic scholar who is an interpreter or expounder of Islamic law." },
    { word: "MUMIN", definition: "A believer, one who has true faith in their heart." },
    { word: "NABIY", definition: "A prophet." },
    { word: "NIFAQ", definition: "Hypocrisy, professing belief while concealing disbelief." },
    { word: "NIKAH", definition: "Marriage contract in Islam." },
    { word: "NIYYA", definition: "Intention, the sincere intention in one's heart to perform an act for the sake of Allah." },
    { word: "QADAR", definition: "Divine decree, predestination." },
    { word: "QALB", definition: "The heart, both the physical organ and the spiritual center." },
    { word: "QIBLA", definition: "The direction that Muslims face during prayer, towards the Kaaba in Mecca." },
    { word: "QIYAM", definition: "Standing, as in the standing position during prayer or voluntary night prayers." },
    { word: "QURAN", definition: "The holy book of Islam, believed to be the word of Allah as revealed to the Prophet Muhammad." },
    { word: "RAHIM", definition: "The Merciful, especially to believers; one of the names of Allah." },
    { word: "RAHMA", definition: "Mercy, compassion." },
    { word: "RAKAT", definition: "A unit of prayer, consisting of a series of prescribed movements and recitations." },
    { word: "RASUL", definition: "A messenger, a prophet sent with a new scripture or law." },
    { word: "RIDDA", definition: "Apostasy, the act of a Muslim leaving Islam." },
    { word: "RIZQ", definition: "Sustenance, provision from Allah." },
    { word: "SABIR", definition: "Patient, one who practices patience (sabr)." },
    { word: "SABR", definition: "Patience, endurance, and steadfastness." },
    { word: "SAHAB", definition: "Companions of the Prophet Muhammad." },
    { word: "SAHIH", definition: "Authentic, sound; used to describe the most reliable category of hadith." },
    { word: "SAJDA", definition: "Prostration, the act of bowing down in worship." },
    { word: "SALAH", definition: "The ritual prayer performed five times a day, one of the Five Pillars of Islam." },
    { word: "SALAM", definition: "Peace, a common greeting among Muslims; one of the names of Allah." },
    { word: "SAMAD", definition: "The Eternal, The Absolute; one of the names of Allah." },
    { word: "SAUM", definition: "Fasting, especially during the month of Ramadan." },
    { word: "SHAMS", definition: "The sun, mentioned as one of Allah's signs." },
    { word: "SHARI", definition: "Related to the Sharia, Islamic law." },
    { word: "SHIRK", definition: "The sin of associating partners with Allah, polytheism." },
    { word: "SHURA", definition: "Consultation, a principle of governance in Islam." },
    { word: "SIDQ", definition: "Truthfulness, sincerity." },
    { word: "SIRAT", definition: "The path, as in the straight path of Islam." },
    { word: "SIYAM", definition: "Fasting." },
    { word: "SUJUD", definition: "Prostration." },
    { word: "SUNNA", definition: "The way of the Prophet Muhammad, his teachings and practices." },
    { word: "SUNNI", definition: "The largest branch of Islam, which follows the Sunnah of the Prophet Muhammad." },
    { word: "SURAH", definition: "A chapter of the Qur'an." },
    { word: "TAALA", definition: "The Most High, an epithet for Allah." },
    { word: "TALUT", definition: "Saul, a king mentioned in the Qur'an." },
    { word: "TAQWA", definition: "God-consciousness, piety, fear of Allah." },
    { word: "TAWAF", definition: "The ritual of circumambulating the Kaaba." },
    { word: "TAWBA", definition: "Repentance, turning to Allah in remorse for one's sins." },
    { word: "TAWRA", definition: "The Torah, the holy book revealed to Moses." },
    { word: "TRUTH", definition: "The ultimate reality, which in Islam is Allah." },
    { word: "UHUD", definition: "A mountain in Medina and the site of a famous battle." },
    { word: "UMMAH", definition: "The global community of Muslims." },
    { word: "UMRAH", definition: "The lesser pilgrimage to Mecca, which can be performed at any time of the year." },
    { word: "UTHMAN", definition: "The third Caliph of Islam." },
    { word: "UZZA", definition: "A pre-Islamic Arabian goddess." },
    { word: "WAHID", definition: "The One, The Unique; one of the names of Allah." },
    { word: "WAJIB", definition: "An obligatory act, similar to Fard." },
    { word: "WALIY", definition: "A friend, protector, or guardian; often refers to a saint or a friend of Allah." },
    { word: "YAHYA", definition: "John the Baptist, a prophet in Islam." },
    { word: "YUNUS", definition: "Jonah, a prophet who was swallowed by a great fish." },
    { word: "ZABUR", definition: "The Psalms, the holy book revealed to David (Dawud)." },
    { word: "ZAKAT", definition: "Obligatory charity, one of the Five Pillars of Islam." },
    { word: "ZAYD", definition: "A companion and adopted son of the Prophet Muhammad." },

    // 6 Letters
    { word: "ABRAHA", definition: "An Abyssinian general who attempted to destroy the Kaaba." },
    { word: "ADVERS", definition: "Adversity, a trial or hardship." },
    { word: "AHKAM", definition: "Rulings, the divine rulings of Islamic law." },
    { word: "AHMAD", definition: "Another name for the Prophet Muhammad, meaning 'the most praised'." },
    { word: "AKHLAQ", definition: "Morals, ethics, and character in Islam." },
    { word: "ALEEM", definition: "The All-Knowing, one of the names of Allah." },
    { word: "AMEEN", definition: "Amen, said after a prayer." },
    { word: "AMANAH", definition: "Trust, a sacred trust or responsibility given by Allah." },
    { word: "ANGELS", definition: "Spiritual beings who serve Allah." },
    { word: "ANSAR", definition: "The helpers, the Muslims of Medina." },
    { word: "AQIDAH", definition: "Creed, the set of Islamic beliefs." },
    { word: "ARAFAH", definition: "The Day of Arafah, a pivotal day of Hajj." },
    { word: "ASHURA", definition: "The tenth day of Muharram, a day of voluntary fasting." },
    { word: "AZRAIL", definition: "The Angel of Death in some Islamic traditions." },
    { word: "BAQARA", definition: "The Cow, the second and longest chapter of the Qur'an." },
    { word: "BARZAK", definition: "The intermediary state between death and the Day of Resurrection." },
    { word: "BASIRA", definition: "Insight, spiritual perception." },
    { word: "BATTLE", definition: "A significant historical conflict, like the Battle of Badr." },
    { word: "BISMIL", definition: "In the name of, the beginning of 'Bismillah'." },
    { word: "CALIPH", definition: "A successor to the Prophet Muhammad and the leader of the Muslim community." },
    { word: "DAJJAL", definition: "The Antichrist, a false messiah who is believed to appear before the Day of Judgment." },
    { word: "DAVID", definition: "Dawud, a prophet and king in Islam." },
    { word: "DAWOOD", definition: "David, a prophet to whom the Zabur (Psalms) was revealed." },
    { word: "DHIKIR", definition: "Remembrance of Allah." },
    { word: "DIRHAM", definition: "A silver coin used in the past in several Muslim countries." },
    { word: "FAITH", definition: "Iman, belief in Allah and the tenets of Islam." },
    { word: "FATIMA", definition: "The daughter of the Prophet Muhammad and the wife of Ali ibn Abi Talib." },
    { word: "FIDYAH", definition: "A charitable donation made for missing fasts for a valid reason." },
    { word: "FITNAH", definition: "Trial, tribulation, or civil strife." },
    { word: "FITRAH", definition: "The innate, natural disposition of a human being to worship Allah." },
    { word: "FURQAN", definition: "The Criterion, another name for the Qur'an, as it distinguishes between right and wrong." },
    { word: "GHAFLA", definition: "Heedlessness, negligence in remembering Allah." },
    { word: "GHAYB", definition: "The unseen world." },
    { word: "HADEES", definition: "A narration of the Prophet Muhammad's words or deeds." },
    { word: "HADITH", definition: "A collection of traditions containing sayings of the prophet Muhammad which, with accounts of his daily practice (the Sunna), constitute the major source of guidance for Muslims apart from the Koran." },
    { word: "HALIM", definition: "The Forbearing, one of the names of Allah." },
    { word: "HANBAL", definition: "A major school of Islamic jurisprudence (fiqh)." },
    { word: "HANIF", definition: "One who follows the pure monotheistic religion of Abraham." },
    { word: "HARUT", definition: "An angel mentioned in the Qur'an, sent as a trial." },
    { word: "HASANA", definition: "A good deed, a reward from Allah." },
    { word: "HIJAMA", definition: "Cupping therapy, a practice recommended by the Prophet Muhammad." },
    { word: "HIJRAH", definition: "The migration from Mecca to Medina." },
    { word: "HIKMAH", definition: "Wisdom." },
    { word: "HUDHUD", definition: "The hoopoe bird, mentioned in the story of Prophet Solomon." },
    { word: "IBADAH", definition: "Worship, any act of obedience to Allah." },
    { word: "IDDAH", definition: "The waiting period a woman must observe after the death of her husband or after a divorce." },
    { word: "IFTAAR", definition: "The meal eaten by Muslims after sunset to break the daily fast during Ramadan." },
    { word: "IKHLAS", definition: "Sincerity, purity of intention; also the name of a chapter in the Qur'an." },
    { word: "IKRAAM", definition: "Honoring, showing generosity." },
    { word: "IMAMAH", definition: "The concept of leadership in Islam." },
    { word: "ISMAIL", definition: "Ishmael, a prophet and the son of Abraham." },
    { word: "JAHIM", definition: "The Blazing Fire, one of the names of Hell." },
    { word: "JANNAH", definition: "Paradise, the Garden." },
    { word: "JIHAAD", definition: "Struggle in the way of Allah." },
    { word: "JUMUAH", definition: "Friday prayer." },
    { word: "KAFALA", definition: "Sponsorship, guardianship in Islamic law." },
    { word: "KHALID", definition: "A famous Muslim general and companion of the Prophet Muhammad." },
    { word: "KHALIQ", definition: "The Creator, one of the names of Allah." },
    { word: "KHIMAR", definition: "A type of head covering for Muslim women." },
    { word: "KHUTBA", definition: "The sermon delivered during the Friday prayer or on other special occasions." },
    { word: "LAYLAT", definition: "Night, as in 'Laylat al-Qadr'." },
    { word: "MADINA", definition: "Medina, the city of the Prophet." },
    { word: "MAHRAM", definition: "An unmarriageable kin with whom marriage is forbidden." },
    { word: "MAKKAH", definition: "Mecca, the holiest city in Islam." },
    { word: "MAKROO", definition: "A disliked or abominable act in Islam." },
    { word: "MARIAM", definition: "Mary, the mother of Jesus." },
    { word: "MARUF", definition: "That which is good, right, and well-known." },
    { word: "MASJID", definition: "A mosque, a place of prostration." },
    { word: "MAWLA", definition: "Master, protector, or patron." },
    { word: "MAWLID", definition: "The observance of the birthday of the Prophet Muhammad." },
    { word: "MERCY", definition: "Rahmah, a key attribute of Allah." },
    { word: "MIRAAJ", definition: "The Ascension of the Prophet Muhammad to the heavens." },
    { word: "MIRACLE", definition: "An extraordinary event attributed to divine intervention, performed by a prophet." },
    { word: "MIZAN", definition: "The scale on which deeds will be weighed on the Day of Judgment." },
    { word: "MUAWIA", definition: "The founder of the Umayyad Caliphate." },
    { word: "MUEZZI", definition: "The person who proclaims the call to prayer (Adhan)." },
    { word: "MUHAJI", definition: "A Muhajir, one who migrated from Mecca to Medina." },
    { word: "MUHSIN", definition: "One who does good deeds and practices Ihsan." },
    { word: "MUNKAR", definition: "That which is wrong or evil; also the name of an angel who questions the dead." },
    { word: "MURSIL", definition: "One who is sent, a messenger." },
    { word: "MUSLIM", definition: "One who submits to the will of Allah; a follower of Islam." },
    { word: "NAFL", definition: "A voluntary act of worship." },
    { word: "NIYYAH", definition: "Intention." },
    { word: "QIBLAH", definition: "The direction of prayer." },
    { word: "QURBAN", definition: "Sacrifice, the ritual animal sacrifice during Eid al-Adha." },
    { word: "RAHEEM", definition: "The Merciful, one of the names of Allah." },
    { word: "RAHMAN", definition: "The Most Gracious, one of the names of Allah." },
    { word: "RASOOL", definition: "A messenger of Allah." },
    { word: "RIDDAH", definition: "Apostasy from Islam." },
    { word: "RISALA", definition: "The message of Islam; prophethood." },
    { word: "SABA", definition: "Sheba, an ancient kingdom mentioned in the Qur'an." },
    { word: "SADAQA", definition: "Voluntary charity." },
    { word: "SAHABA", definition: "The companions of the Prophet Muhammad." },
    { word: "SAHABI", definition: "A male companion of the Prophet Muhammad." },
    { word: "SAHEEH", definition: "Authentic (hadith)." },
    { word: "SAJDAH", definition: "Prostration in prayer." },
    { word: "SAKINA", definition: "Divine tranquility, peace, and serenity." },
    { word: "SALAAT", definition: "Ritual prayer." },
    { word: "SALMAN", definition: "A famous Persian companion of the Prophet Muhammad." },
    { word: "SALSABIL", definition: "A spring or fountain in Paradise." },
    { word: "SHAHEED", definition: "A martyr, one who dies in the cause of Allah." },
    { word: "SHAYKH", definition: "A respectful title for a scholar or an elder." },
    { word: "SIDRAH", definition: "The Lote Tree of the Utmost Boundary in the seventh heaven." },
    { word: "SIRAAT", definition: "The path, especially the bridge over Hell on the Day of Judgment." },
    { word: "SUHOOR", definition: "The pre-dawn meal eaten by Muslims before fasting during Ramadan." },
    { word: "SULTAN", definition: "A ruler or sovereign in a Muslim country." },
    { word: "SUNNAH", definition: "The practice and example of the Prophet Muhammad." },
    { word: "TABUK", definition: "The site of a military expedition led by the Prophet Muhammad." },
    { word: "TAFSIR", definition: "Exegesis or commentary on the Qur'an." },
    { word: "TAHARA", definition: "Ritual purity and cleanliness." },
    { word: "TALAQ", definition: "Divorce in Islam." },
    { word: "TARTEE", definition: "Reciting the Qur'an slowly and melodiously." },
    { word: "TASBIH", definition: "The glorification of Allah by saying 'Subhanallah'." },
    { word: "TAWBAH", definition: "Repentance." },
    { word: "TAWHID", definition: "The oneness of Allah, the central tenet of Islam." },
    { word: "TAWRAT", definition: "The Torah." },
    { word: "TAYAMM", definition: "Dry ablution with sand or dust when water is not available." },
    { word: "TAYYIB", definition: "Good, pure, and lawful." },
    { word: "USURY", definition: "The practice of lending money at exorbitant rates of interest, forbidden as Riba." },
    { word: "WUDHU", definition: "Ritual ablution before prayer." },
    { word: "YAQEEB", definition: "Jacob, a prophet in Islam." },
    { word: "YAQUB", definition: "Jacob, a prophet and the father of the twelve tribes of Israel." },
    { word: "YATHRB", definition: "The former name of the city of Medina." },
    { word: "YUSUF", definition: "Joseph, a prophet known for his beauty and wisdom." },
    { word: "ZABIHA", definition: "The Islamic method of ritual slaughter." },
    { word: "ZAKAH", definition: "Obligatory charity." },
    { word: "ZAMZAM", definition: "The sacred well in Mecca." },
    { word: "ZAYNAB", definition: "A daughter and a granddaughter of the Prophet Muhammad." },

    // 7 Letters
    { word: "ABRAHAM", definition: "Ibrahim, a major prophet and a central figure in Islam, Judaism, and Christianity." },
    { word: "AQEEDAH", definition: "Creed, the system of Islamic belief." },
    { word: "BARAKAH", definition: "Blessing, an increase in good from Allah." },
    { word: "BELIEF", definition: "Faith (Iman) in the core tenets of Islam." },
    { word: "BELIEVE", definition: "To have faith and trust in Allah." },
    { word: "CHARITY", definition: "Giving to those in need, an important act of worship (Sadaqah/Zakat)." },
    { word: "COMMAND", definition: "An order from Allah, found in the Qur'an." },
    { word: "CREATED", definition: "Brought into existence by Allah." },
    { word: "CREATOR", definition: "The one who brings everything into existence; Allah (Al-Khaliq)." },
    { word: "FARAID", definition: "The obligatory duties in Islam; also refers to Islamic inheritance laws." },
    { word: "FATIHAH", definition: "The Opening, the first chapter of the Qur'an." },
    { word: "FIRDAUS", definition: "The highest level of Paradise." },
    { word: "FORGIVE", definition: "To grant pardon for an offense; a key attribute of Allah (Al-Ghafur)." },
    { word: "GABRIEL", definition: "Jibril, the archangel who delivered the Qur'an to the Prophet Muhammad." },
    { word: "GHAFLAH", definition: "Heedlessness, being forgetful of Allah." },
    { word: "GUIDANCE", definition: "Hidayah, divine guidance from Allah." },
    { word: "HADEETH", definition: "A report of the sayings or actions of the Prophet Muhammad." },
    { word: "HANBALI", definition: "Pertaining to the Hanbali school of Islamic law." },
    { word: "HARAAM", definition: "Forbidden or unlawful in Islam." },
    { word: "HASANAT", definition: "Good deeds." },
    { word: "HEAVEN", definition: "Jannah, the paradise for believers." },
    { word: "HIJAAB", definition: "The practice of modest dress for Muslim women, including a headscarf." },
    { word: "IBRAHIM", definition: "Abraham, a revered prophet in Islam." },
    { word: "IMAMATE", definition: "The concept of leadership, especially in Shia Islam." },
    { word: "ISRAFIL", definition: "The angel who will blow the trumpet on the Day of Judgment." },
    { word: "ITIKAF", definition: "A spiritual retreat in a mosque, usually during the last ten days of Ramadan." },
    { word: "JAHANAM", definition: "Hellfire, the place of punishment in the hereafter." },
    { word: "JANAZAH", definition: "The Islamic funeral prayer." },
    { word: "JANNAT", definition: "Gardens of Paradise." },
    { word: "JIBREEL", definition: "Gabriel, the archangel of revelation." },
    { word: "KAAFIR", definition: "A disbeliever." },
    { word: "KHADIJA", definition: "The first wife of the Prophet Muhammad and the first person to convert to Islam." },
    { word: "KHATEEB", definition: "The person who delivers the sermon (khutbah)." },
    { word: "KHILAFA", definition: "The Caliphate, the Islamic system of governance." },
    { word: "KHUTBAH", definition: "The sermon delivered by an imam." },
    { word: "MADINAH", definition: "Medina, the city to which the Prophet Muhammad migrated." },
    { word: "MALAIKA", definition: "Angels." },
    { word: "MESSAGE", definition: "The divine message (Risalah) brought by the prophets." },
    { word: "MIKAIL", definition: "Michael, the archangel responsible for rainfall and sustenance." },
    { word: "MUHARRAM", definition: "The first month of the Islamic calendar and one of the four sacred months." },
    { word: "MUNAFIQ", definition: "A hypocrite, one who feigns belief." },
    { word: "MUSLIMA", definition: "A female Muslim." },
    { word: "PROPHET", definition: "A person chosen by Allah to deliver His message to humanity." },
    { word: "QURAYSH", definition: "The tribe of the Prophet Muhammad." },
    { word: "RAHMAH", definition: "Mercy." },
    { word: "RAMADAN", definition: "The ninth month of the Islamic calendar, during which Muslims fast from dawn to sunset." },
    { word: "RASOOL", definition: "A messenger of Allah." },
    { word: "RUQIYAH", definition: "Divine healing or exorcism using verses from the Qur'an and supplications." },
    { word: "SABEEL", definition: "Path or way, as in the path of Allah." },
    { word: "SADAQAH", definition: "Voluntary charity." },
    { word: "SAHABAH", definition: "The companions of the Prophet Muhammad." },
    { word: "SAKINAH", definition: "Divine tranquility." },
    { word: "SALAAM", definition: "Peace, a greeting." },
    { word: "SHAHADA", definition: "The declaration of faith, one of the Five Pillars of Islam." },
    { word: "SHARIAH", definition: "Islamic law, based on the Qur'an and the Sunnah." },
    { word: "SHAWWAL", definition: "The tenth month of the Islamic calendar, following Ramadan." },
    { word: "SHAYTAN", definition: "Satan, the Devil." },
    { word: "SUBHAN", definition: "Glory, as in 'Subhanallah' (Glory be to Allah)." },
    { word: "TAHARAH", definition: "Ritual purity." },
    { word: "TAHAJUD", definition: "Voluntary night prayers." },
    { word: "TAHLIL", definition: "The recitation of 'La ilaha illallah' (There is no god but Allah)." },
    { word: "TARAWIH", definition: "Special voluntary prayers performed during the nights of Ramadan." },
    { word: "TAWAKUL", definition: "Trust and reliance on Allah." },
    { word: "TAWHEED", definition: "The doctrine of the oneness of Allah." },
    { word: "ZAKARIYA", definition: "Zechariah, a prophet and the father of John the Baptist." }
];
