// A comprehensive list of English Islamic-themed words for the game.
// This list enables fully offline gameplay in English.
export const en_words: string[] = [
    // 4 Letters
    "ADAM", "ADIL", "AMAN", "AMIN", "ASR", "AYAH", "CALM", "DATE", "DAWA", "DEED", "DEEN", "DOVE", 
    "DUAA", "EDEN", "FAJR", "FARD", "FAST", "FATE", "FEAR", "FIQH", "FOOD", "GIFT", "GIVE", "GOAL", 
    "GOOD", "HAJJ", "HALA", "HAQQ", "HEAL", "HEED", "HEIR", "HELP", "HIJR", "HOPE", "HOUR", "HURI", 
    "ILM", "IMAM", "IMAN", "ISA", "JINN", "KAAB", "KIND", "LAIL", "LIFE", "LOVE", "LUT", "MARY", 
    "MEAL", "MINA", "MOON", "MUSA", "NABI", "NAFS", "NOAH", "NOOR", "OATH", "OMAR", "PALM", "PATH", 
    "PRAY", "PURE", "QADR", "RAMI", "READ", "RIBA", "RUH", "RULE", "SAFA", "SAFE", "SAWM", "SEEK", 
    "SHIA", "SOUL", "STAR", "SUFI", "SURA", "TAWF", "TEST", "TRUE", "TUR", "UMMA", "UTHM", "VEIL", 
    "WAHY", "WIRD", "WISE", "WOMB", "WORD", "WUDU", "ZABI", "ZIKR",

    // 5 Letters
    "AARAF", "ABBAS", "ABDUL", "ADAB", "ADHAN", "AHAD", "AKBAR", "ALLAH", "ANGEL", "ANSAR", "AQIDA", 
    "AQSA", "ARABS", "ASMA", "AWRAH", "AYATS", "BADR", "BARAK", "BASIR", "BATIN", "BILAL", "BLESS", 
    "BURAQ", "DAWAH", "DEEDS", "DHIKR", "DINAR", "DREAM", "DUAAS", "EID", "FATIH", "FATWA", "GHAIB", 
    "GHUSL", "GRACE", "HADIS", "HAFIZ", "HAJAR", "HALAL", "HARAM", "HIJAB", "HIJRA", "HIJRI", "HIKMA", 
    "HUDUD", "IBLIS", "IHSAN", "IJMAA", "IKRAM", "ILAHI", "ILYAS", "IMAMA", "INJIL", "ISHAQ", "ISLAM", 
    "ISRA", "JABIR", "JANNA", "JIHAD", "JUMMA", "KABAH", "KABIR", "KAFIR", "KALAM", "KARIM", "KHAYR", 
    "KISWA", "KITAB", "LAWHI", "LAYLA", "MAHDI", "MAKKA", "MALAK", "MALIK", "MANAT", "MARUT", "MARWA", 
    "MASIH", "MECCA", "MEDINA", "MIKAL", "MINAR", "MISWK", "MOSES", "MOSQUE", "MUFTI", "MUMIN", "NABIY", 
    "NIFAQ", "NIKAH", "NIYYA", "QADAR", "QALB", "QIBLA", "QIYAM", "QURAN", "RAHIM", "RAHMA", "RAKAT", 
    "RASUL", "RIDDA", "RIZQ", "SABIR", "SABR", "SAHAB", "SAHIH", "SAJDA", "SALAH", "SALAM", "SAMAD", 
    "SAUM", "SHAMS", "SHARI", "SHIRK", "SHURA", "SIDQ", "SIRAT", "SIYAM", "SUJUD", "SUNNA", "SUNNI", 
    "SURAH", "TAALA", "TALUT", "TAQWA", "TAWAF", "TAWBA", "TAWRA", "TRUTH", "UHUD", "UMMAH", "UMRAH", 
    "UTHMAN", "UZZA", "WAHID", "WAJIB", "WALIY", "YAHYA", "YUNUS", "ZABUR", "ZAKAT", "ZAYD",

    // 6 Letters
    "ABRAHA", "ADVERS", "AHKAM", "AHMAD", "AKHLAQ", "ALEEM", "AMEEN", "AMANAH", "ANGELS", "ANSAR", 
    "AQIDAH", "ARAFAH", "ASHURA", "AZRAIL", "BAQARA", "BARZAK", "BASIRA", "BATTLE", "BILAL", 
    "BISMIL", "CALIPH", "DAJJAL", "DAVID", "DAWOOD", "DHIKIR", "DIRHAM", "FAITH", "FATIMA", 
    "FIDYAH", "FITNAH", "FITRAH", "FURQAN", "GHAFLA", "GHAYB", "HADEES", "HADITH", "HALIM", 
    "HANBAL", "HANIF", "HARUT", "HASANA", "HIJAMA", "HIJRAH", "HIKMAH", "HUDHUD", "IBADAH", "IDDAH", 
    "IFTAAR", "IKHLAS", "IKRAAM", "IMAMAH", "ISMAIL", "JAHIM", "JANNAH", "JIHAAD", "JUMUAH", 
    "KAFALA", "KHALID", "KHALIQ", "KHIMAR", "KHUTBA", "LAYLAT", "MADINA", "MAHRAM", "MAKKAH", 
    "MAKROO", "MARIAM", "MARUF", "MASJID", "MAWLA", "MAWLID", "MEDINA", "MERCY", "MIRAAJ", "MIRACLE", 
    "MIZAN", "MUAWIA", "MUEZZI", "MUHAJI", "MUHSIN", "MUMIN", "MUNKAR", "MURSIL", "MUSLIM", "NAFL", 
    "NIYYAH", "QIBLAH", "QURBAN", "RAHEEM", "RAHMAN", "RASOOL", "RIDDAH", "RISALA", "SABA", 
    "SADAQA", "SAHABA", "SAHABI", "SAHEEH", "SAJDAH", "SAKINA", "SALAAT", "SALMAN", "SALSABIL", 
    "SHAHEED", "SHAYKH", "SIDRAH", "SIRAAT", "SUHOOR", "SULTAN", "SUNNAH", "TABUK", "TAFSIR", 
    "TAHARA", "TALAQ", "TAQWA", "TARTEE", "TASBIH", "TAWBAH", "TAWHID", "TAWRAT", "TAYAMM", "TAYYIB", 
    "UMRAH", "USURY", "WUDHU", "YAQEEB", "YAQUB", "YATHRB", "YUSUF", "ZABIHA", "ZAKAH", "ZAMZAM", "ZAYNAB",

    // 7 Letters
    "ABRAHAM", "AQEEDAH", "BARAKAH", "BELIEF", "BELIEVE", "CHARITY", "COMMAND", "CREATED", "CREATOR", 
    "FARAID", "FATIHAH", "FIRDAUS", "FORGIVE", "GABRIEL", "GHAFLAH", "GUIDANCE", "HADEETH", "HANBALI", 
    "HARAAM", "HASANAT", "HEAVEN", "HIJAAB", "IBRAHIM", "IMAMATE", "ISRAFIL", "ITIKAF", "JAHANAM", 
    "JANAZAH", "JANNAT", "JIBREEL", "KAAFIR", "KHADIJA", "KHATEEB", "KHILAFA", "KHUTBAH", "MADINAH", 
    "MALAIKA", "MESSAGE", "MIKAIL", "MUHARRAM", "MUNAFIQ", "MUSLIMA", "PROPHET", "QURAYSH", "RAHMAH", 
    "RAMADAN", "RASOOL", "RUQIYAH", "SABEEL", "SADAQAH", "SAHABAH", "SAKINAH", "SALAAM", "SALAAT", 
    "SHAHADA", "SHARIAH", "SHAWWAL", "SHAYTAN", "SUBHAN", "TAHARAH", "TAHAJUD", "TAHLIL", "TARAWIH", 
    "TAWAKUL", "TAWHEED", "ZAKARIYA"
];
