// A comprehensive list of Turkish Islamic-themed words for the game.
// This list enables fully offline gameplay.
export const tr_words: string[] = [
    // 4 Harfli Kelimeler
    "ABES", "ACEM", "ADAK", "ADAP", "ADEM", "ADİL", "AFET", "AFİF", "AFÜV", "AHAD", "AHİT", "AKİF",
    "AKIL", "AKİT", "AKLI", "AKRA", "ALEM", "ALİM", "ALİY", "AMEL", "AMİL", "ANKA", "ARAF", "ARİF",
    "ATEH", "AVAM", "AYET", "AYİN", "AYIP", "AYŞE", "AZAB", "AZAP", "AZAT", "AZİM", "AZİZ", "AŞAR",
    "AŞIR", "BAKİ", "BEDİ", "BEKA", "BELA", "BERR", "BİAT", "BİRR", "BUĞZ", "BÂRÎ", "BÜYÜ", "CAİZ",
    "CAMİ", "CERH", "CEVA", "CEZA", "CUDİ", "CUMA", "CÜRM", "DEDE", "DEFN", "DOST", "ECEL", "ECİR",
    "EDEB", "EDEP", "EHAD", "ELÇİ", "EMAN", "EMİN", "EMİR", "ENAM", "EREN", "ESER", "ESRA", "EZAN",
    "EZEL", "FAKA", "FAKR", "FARZ", "FAİZ", "FECR", "FERA", "FETA", "FETH", "FEYZ", "FISK", "FUHŞ",
    "FÜCU", "GASP", "GAVS", "GAYB", "GAZA", "GAZİ", "GÜNÜ", "HACC", "HACI", "HAMR", "HAMT", "HATA",
    "HAVF", "HAYÂ", "HAŞA", "HAŞR", "HEVA", "HEZL", "HIRS", "HIZ", "HİBE", "HİCR", "HİDA", "HİZB",
    "HOCA", "HUDA", "HUHU", "HURİ", "HUSU", "HUŞU", "HÂDİ", "HIFZ", "HIKD", "HÜKM", "HÜSN", "ICAR",
    "İCAZ", "İCMA", "İÇKİ", "İFTA", "İĞVA", "İHTİ", "İHYA", "İKAB", "İKTA", "İLAH", "İLİM", "İLMİ",
    "İMAM", "İMAN", "İNAM", "İSAR", "İSRA", "KABE", "KADE", "KADI", "KAFİ", "KALP", "KAVİ", "KAZA",
    "KAZF", "KEŞF", "KÖLE", "KÜFR", "KURU", "LAHN", "LAĞV", "MAHV", "MARİ", "MAZI", "MEAL", "MENİ",
    "MESH", "MEST", "MEZİ", "MİHR", "MİNA", "MUİD", "MUİZ", "MUTİ", "NAAŞ", "NAAT", "NASS", "NEBİ",
    "NEHY", "NESH", "NEZR", "NOEL", "ORUÇ", "ÖLÜM", "ÖŞÜR", "ÖZÜR", "PAPA", "RABB", "RADA", "RAFİ",
    "RAKK", "RAUF", "RAVİ", "RECA", "RIFK", "RIZA", "RİBA", "RİCS", "RİYA", "RÜKÛ", "RÜŞD", "RÜŞT",
    "SAAT", "SABR", "SAFA", "SAHU", "SAİT", "SALA", "SAVM", "SEMA", "SEMİ", "SIDK", "SİKA", "SUFİ",
    "SULH", "SURE", "ŞAKİ", "ŞARİ", "ŞART", "ŞAVT", "ŞERH", "ŞERİ", "ŞEYH", "ŞİRK", "ŞÛRA", "ŞÜKR",
    "TABU", "TUBA", "UMRE", "UZZA", "ÜMMİ", "VAAZ", "VAHY", "VAİZ", "VALİ", "VASİ", "VECD", "VEDA",
    "VEDİ", "VEFA", "VELİ", "VERA", "VİRD", "YEİS", "YUŞA", "ZAPT", "ZİKR", "ZİNA", "ZULM", "ZÜHT",
    "ÂBİT", "ÂDEM", "ÂDET", "ÂHİR", "ÂLEM", "ÂMİN", "ÇİLE",

    // 5 Harfli Kelimeler
    "ABDAL", "ACEMÎ", "ADAVE", "ADNAN", "AĞACI", "AHBAR", "AHLAK", "AHYAR", "AKABE", "AKAİT", "AKİDE",
    "AKİKA", "ALEVİ", "ALEYH", "ALLAH", "AREFE", "ARİFE", "ARRAF", "ASHAB", "AŞURE", "AVRET", "AYLAR",
    "BAHAİ", "BALİĞ", "BASAR", "BASÎR", "BATIL", "BÂTIN", "BEKKE", "BELAM", "BERAT", "BETÜL", "BEYAN",
    "BEŞİR", "BİDAT", "BİSET", "BUĞUZ", "BURAK", "BÜLUĞ", "CAHİL", "CAHİM", "CEDEL", "CELAL", "CELİL",
    "CEMAA", "CENİN", "CEVAZ", "CEZBE", "CİDAL", "CİHAT", "CİMRİ", "CİZYE", "CÜBBE", "CÜLUS", "CÜNAH",
    "CÜNUN", "CÜNÜP", "CÜRÜM", "ÇALAP", "DAVET", "DEFİN", "DEHRİ", "DELİL", "DEYİŞ", "DİDAR", "DİVAN",
    "DİYET", "EBCET", "EBDAL", "EBRAR", "EBTER", "EFDAL", "EKREM", "ENFAL", "ENSAR", "ERVAH", "EŞARÎ",
    "EVKAF", "EVRAD", "EVVEL", "EYVAL", "EZELÎ", "EZLAM", "FACİR", "FAHİŞ", "FAKİH", "FAKİR", "FASIK",
    "FASİT", "FECİR", "FELAH", "FESAD", "FESAT", "FESİH", "FETİH", "FETVA", "FEYİZ", "FIKIH", "FIRKA",
    "FITRA", "FİDYE", "FİTEN", "FİTNE", "FİTRE", "FUHUŞ", "FÜCUR", "GAFUR", "GALAT", "GARİP", "GASİL",
    "GAZAB", "GAZAP", "GAZVE", "GIPTA", "GIYAR", "GÖNLÜ", "GÖNÜL", "GURRE", "GUSÜL", "GÜNAH", "GÂVUR",
    "HABİL", "HABİS", "HABÎR", "HADES", "HADİS", "HAFIZ", "HAFÎZ", "HAHAM", "HAKEM", "HAKÎM", "HALİL",
    "HALÎM", "HAMÎD", "HANİF", "HARAÇ", "HARAM", "HAREM", "HASET", "HASİS", "HASÎB", "HAŞİR", "HATİM",
    "HATİP", "HATÎM", "HAVAS", "HAVLE", "HAVRA", "HAYAT", "HAYIR", "HAYIZ", "HELAL", "HICAB", "HİCAP",
    "HİCAZ", "HİLAF", "HİLAL", "HİLİM", "HİLYE", "HİTAN", "HİYEL", "HİZİP", "HULUL", "HUMUS", "HUTBE",
    "HUZUR", "HZALİ", "HÂFID", "HÂKİM", "HÂLIK", "HIZIR", "HÜBEL", "HÜKÜM", "HÜLLE", "HÜNSA", "HÜSNA",
    "HÜSÜN", "ISKAT", "ISLAH", "İBAHA", "İBLİS", "İBRET", "İDDET", "İFADA", "İFFET", "İFLAS", "İFRAT",
    "İFRİT", "İFSAT", "İFTAR", "İHBAT", "İHLAS", "İHRAM", "İHSAN", "İHSAR", "İHVAN", "İKRAR", "İKRAH",
    "İLAHİ", "İLAHÎ", "İLHAD", "İLHAM", "İLLET", "İMAME", "İMARE", "İMSAK", "İNABE", "İNFAK", "İNKÂR",
    "İNSAN", "İNZAL", "İNZAR", "İRADE", "İRFAN", "İRHAS", "İRŞAT", "İSMET", "İSNAT", "İSRAF", "İSTİH",
    "İTAAT", "İTLAF", "İYAFE", "İZZET", "KABİL", "KABİR", "KADER", "KADİR", "KAMET", "KARUN", "KASEM",
    "KÂBID", "KÂFİR", "KÂHİN", "KEBİR", "KEFEN", "KEFİL", "KELAM", "KERİM", "KEŞİŞ", "KIBİR", "KIBLE",
    "KIDEM", "KISAS", "KISSA", "KIYAM", "KIYAS", "KİTAB", "KİTAP", "KUDÜS", "KUMAR", "KUNUT", "KURAN",
    "KURRA", "KUTUB", "KUTUP", "KÜFRE", "KÜFRÜ", "KÜFÜR", "KÜFÜV", "KÜRSİ", "KÜRSÜ", "LAKAP", "LANET",
    "LATİF", "LÜTUF", "MABED", "MABET", "MABUD", "MABUT", "MACİD", "MAHYA", "MAKAM", "MALİK", "MARUF",
    "MARUT", "MASUM", "MATUH", "MAZUR", "MECİD", "MECÜC", "MEHDİ", "MEHİR", "MEKKE", "MELEK", "MELİK",
    "MELUN", "MEMNU", "MENAT", "MERVE", "MESİH", "METAF", "METİN", "MEVLA", "MEYTE", "MEZAR", "MEŞRU",
    "MİKAT", "MİRAC", "MİRAÇ", "MİRAS", "MİSAK", "MİZAN", "MOLLA", "MUBAH", "MUHSİ", "MUKİM", "MUKİT",
    "MUĞNİ", "MUSKA", "MÜBDİ", "MÜFTÜ", "MÜMİN", "MÜMİT", "MÜRİT", "MÜZİL", "NAMAZ", "NAMUS", "NASİH",
    "NAZAR", "NECEŞ", "NEFİS", "NEFSİ", "NEHİY", "NESAİ", "NESEB", "NESEP", "NEZİR", "NİFAK", "NİFAS",
    "NİKÂH", "NİMET", "NİSAP", "NİYET", "OLMAK", "PAGAN", "PAPAZ", "RAHİM", "RAHİP", "RAHLE", "RAKIB",
    "RAKIM", "RAŞİT", "RECEP", "RECİM", "REHİN", "REKÂT", "REMEL", "RESUL", "REŞİD", "REŞİT", "RIHLE",
    "RIZIK", "RIZKI", "RİBAT", "RİKAZ", "RUKYE", "RÜKÜN", "SABIR", "SABİİ", "SABUR", "SADAK", "SADAT",
    "SADIK", "SAHUR", "SALAT", "SALİH", "SALİK", "SALİP", "SAMED", "SARIK", "SEBİL", "SECCA", "SECDE",
    "SEFİH", "SEHER", "SELAM", "SELEM", "SENET", "SEVAB", "SEVAP", "SEYİT", "SİHİR", "SİYER", "SUHUF",
    "SUNUŞ", "SÜCUD", "SÜNEN", "SÜNNİ", "SÜTRE", "ŞABAN", "ŞABAT", "ŞAFİİ", "ŞAHİT", "ŞAMAN", "ŞEHİD",
    "ŞEHİT", "ŞEKÛR", "ŞERİF", "ŞERİK", "ŞÜKÜR", "TABUT", "TADİL", "TAĞUT", "TAKKE", "TAKVA", "TALAK",
    "TANAH", "TASAV", "TAVAF", "TAZİM", "TAZİR", "TEALA", "TEFRİ", "TEKKE", "TEVİL", "TUFAN", "TÖVBE",
    "TÜRBE", "UZLET", "ÜLFET", "ÜMMET", "VACİP", "VAHİD", "VAHİY", "VAKAR", "VAKFE", "VAKIF", "VAKİT",
    "VAKTİ", "VATAN", "VEBAL", "VEDİA", "VEDÛD", "VEKİL", "VİTİR", "VÂKIF", "VÂRİS", "VÜCUH", "VÜCUT",
    "YAHYA", "YAKÎN", "YALAN", "YEMİN", "YETİM", "YOBAZ", "YORTU", "ZAHİR", "ZAHİT", "ZAKİR", "ZALİM",
    "ZEBUR", "ZEKÂT", "ZELLE", "ZIHAR", "ZİKİR", "ZİKRİ", "ZİMMİ", "ZULÜM",

    // 6 Harfli Kelimeler
    "ABDEST", "ADALET", "ADAVET", "AFOROZ", "AFİYET", "AHADİS", "AHİLİK", "AHİRET", "AHMEDÖ",
    "AKRABA", "ALAMET", "AMENNA", "AMENTÜ", "ARAFAT", "ARASAT", "ATEİST", "ATEİZM", "AZAZİL",
    "AZİMET", "AZRAİL", "BAYRAM", "BEDDUA", "BELKIS", "BERZAH", "BİLLAH", "BUDİZM", "BUHARİ",
    "BURHAN", "BÜHTAN", "CAFERÎ", "CARİYE", "CEBBAR", "CEMAAT", "CENAZE", "CENNET", "CİBRİL",
    "CÖMERT", "CUMHUR", "ÇARMIH", "ÇELEBİ", "DECCAL", "DERGÂH", "DERVİŞ", "DESTUR", "DİNDAR",
    "DİRHEM", "EBABİL", "EHLİSA", "ELMÂNİ", "EMANET", "ENBİYA", "ERBAİN", "ESATİR", "ESMAYI",
    "EVLİYA", "FARİZA", "FASILA", "FATIMA", "FERAİZ", "FETTAH", "FITRAT", "FUKAHA", "FUKARA",
    "FURKAN", "GAFFAR", "GAFLET", "GALİYE", "GASSAL", "GECESİ", "GILMAN", "GIYBET", "GUFRAN",
    "GURBET", "HAKDİN", "HALİFE", "HALİME", "HALVET", "HAMAİL", "HANEFİ", "HANKÂH", "HANNAS",
    "HASENE", "HAŞİMİ", "HAŞİYE", "HAŞYET", "HAVARİ", "HAVİYE", "HAYRAT", "HAZRET", "HEYBET",
    "HICABE", "HİCRET", "HİDANE", "HİKMET", "HİMMET", "HUDARÎ", "HURAFE", "HUTAME", "HIZLAN",
    "HZMUSA", "HZÖMER", "HÜCCET", "HÜNKÂR", "HÜRMÜZ", "HÜSRAN", "HÜTHÜT", "IKERİM", "IZTIBA",
    "İBADET", "İCABET", "İCAZET", "İFTİRA", "İHANET", "İHTİDA", "İKİNDİ", "İKAMET", "İKTİDA",
    "İMAMET", "İNANÇ", "İNAYET", "İNCİL", "İSEVİ", "İSLAM", "İSTİLA", "İSTİVA", "İTİDAL",
    "İTİKAT", "İTİKÂF", "İTTİKA", "KADİRİ", "KAHHAR", "KANAAT", "KAYYUM", "KEBİRE", "KEFAET",
    "KEVSER", "KILİSE", "KIRAAT", "KİTABİ", "KUDDUS", "KUDRET", "KURBAN", "LOKMAN", "MAAZAL",
    "MAHCUR", "MAHFİL", "MAHREM", "MAHŞER", "MAKBER", "MALİKİ", "MASİVA", "MAUNET", "MECUSİ",
    "MECZUP", "MEDİNE", "MEDYEN", "MEGAZİ", "MEKRUH", "MENDUP", "MENNAN", "MENSUH", "MERHUM",
    "MESBUK", "MESCİD", "MESCİT", "MEVİZE", "MEVLİT", "MEYSİR", "MEZHEP", "MEZMUR", "MİHRAP",
    "MİKAİL", "MİLLET", "MİNARE", "MİNBER", "MİNHAC", "MİSKİN", "MİSVAK", "MUAHAT", "MUCİZE",
    "MUHLİS", "MUHRİM", "MUHSAN", "MUHSAR", "MUHSİN", "MUKSİT", "MURDAR", "MUSEVİ", "MUSHAF",
    "MÜDRİK", "MÜFLİS", "MÜFSİT", "MÜKREH", "MÜLHİT", "MÜNKER", "MÜNKİR", "MÜRCİE", "MÜRTET",
    "MÜRŞİD", "MÜRŞİT", "MÜSKİR", "MÜSLİM", "MÜSNET", "MÜSRİF", "MÜTREF", "MÜŞRİK", "NAFAKA",
    "NAFİLE", "NAMAZI", "NANKÖR", "NASARA", "NEMİME", "NEMRUT", "NEZAİR", "ONEMİR", "PATRİK",
    "RABITA", "RAFIZİ", "RAHİBE", "RAHMAN", "RAHMET", "RAKABE", "REFREF", "REZZAK", "RIDVAN",
    "RIHLET", "RİDDET", "RİFADE", "RUHBAN", "RUHANİ", "RUHSAT", "RÜŞVET", "RÜVVET", "SADAKA",
    "SAHABE", "SAMİRİ", "SEFERÎ", "SEYYİE", "SIDDIK", "SİCCİN", "SİKAYE", "SÜNNET", "ŞECAAT",
    "ŞEFAAT", "ŞEREFE", "ŞERİAT", "ŞEVVAL", "ŞEHVET", "ŞEYTAN", "ŞİİLİK", "ŞÜHEDA", "TABİİN",
    "TAHRİF", "TAKDİS", "TAKLİT", "TALMUT", "TASDİK", "TAYYİB", "TAZİYE", "TEBLİĞ", "TEBZİR",
    "TECVİT", "TEDVİN", "TEENNİ", "TEFSİR", "TEHLİL", "TEKBİR", "TEKBÎR", "TEÇHİZ", "TEKFİN",
    "TEKFİR", "TEKVİN", "TELFİK", "TELKİN", "TEMYİZ", "TENZİH", "TENZİL", "TEREKE", "TERTİL",
    "TESBİH", "TESLİS", "TESPİH", "TEVAZU", "TEVFİK", "TEVHİT", "TEVRAT", "TUĞYAN", "TÜVVET",
    "UHREVİ", "UKUBAT", "ÜZEYİR", "VAFTİZ", "VECİBE", "VEDİZM", "VEHHAB", "VELİME", "VESİLE",
    "VİCDAN", "VUSLAT", "YESRİB", "ZAKKUM", "ZAVİYE", "ZEBANİ", "ZEMZEM", "ZIMMET", "ZINDIK",
    "ZİYADÖ", "ZÜLFİK", "ZÜNNAR", "ZÜNNUN", "ÂLİABA",

    // 7 Harfli Kelimeler
    "ABADİLE", "ABDİYET", "AKŞAMNA", "ALPEREN", "ASİTANE", "BABİLİK", "BASİRET", "BAYRAMI",
    "BEKTAŞİ", "BELAGAT", "BEREKET", "BESMELE", "BEYYİNE", "BİLLAHİ", "BOŞANMA", "CEBRAİL",
    "CEBRİYE", "CENABET", "DALALET", "DEHRİYE", "DİLENCİ", "DİNGÜNÜ", "DİYANET", "EBEVEYN",
    "EHLİHAK", "EHLİHÂL", "EHLİREY", "EHLİYET", "EHRİMEN", "ELGAFUR", "EMANETE", "EMRİBİL",
    "EMRİHAK", "FAZİLET", "FELSEFE", "FERASET", "FETANET", "FİRASET", "FİRAVUN", "FİRDEVS",
    "GANİMET", "HAKİKAT", "HALETME", "HAMDELE", "HAMETİM", "HAMİYET", "HANBELİ", "HASENAT",
    "HAVATIR", "HAVKALE", "HERVELE", "HIDAYET", "HİLAFET", "HİTABET", "HIYANET", "HUSUMET",
    "HZHASAN", "HZHAVVA", "HZOSMAN", "HZÂMİNE", "İBRANİ", "İÇTİHAD", "İÇTİHAT", "İHTİKAR",
    "İHTİLAF", "İHTİLAM", "İHTİLAT", "İHTİYAT", "İKTİBAS", "İKTİSAT", "İLMİHÂL", "İMAMEYN",
    "İNTİHAR", "İNTİSAP", "İRTİDAT", "İSRAİL", "İSTİAZE", "İSTİBRA", "İSTİHZA", "İSTİLAM",
    "İSTİNCA", "İSTİRCÂ", "İSTİSKA", "İZDİVAÇ", "ISTILAM", "KATOLİK", "KEFALET", "KEFARET",
    "KEHANET", "KEMAYET", "KERAHET", "KERAMET", "KIYAMET", "LAHAVLE", "LEBBEYK", "MARİFET",
    "MASİYET", "MAZMAZA", "MECELLE", "MEDRESE", "MENASİK", "MENKIBE", "MERHABA", "MESNEVİ",
    "MESTURE", "MEVHİBE", "MEZHEBİ", "MİSAFİR", "MUHACİR", "MUKTEDİ", "MUSALLA", "MUSALLİ",
    "MUTTAKİ", "MUVATTA", "MÜBAREK", "MÜCAHİT", "MÜEZZİN", "MÜHTEDİ", "MÜNACAT", "MÜNAFIK",
    "MÜRAHİK", "MÜRTECİ", "NASİHAT", "NASRANİ", "NECASET", "NEZAFET", "NEZAHET", "ÖRTÜNME",
    "RABBANİ", "RAMAZAN", "RAVZAYI", "RİSALET", "RİVAYET", "RİYAKÂR", "RİYAZET", "SADAKAT",
    "SAHİHAN", "SALVELE", "SECCADE", "SECDESİ", "SERİYYE", "SİNAGOG", "ŞEHADET", "ŞEYHAYN",
    "TAASSUB", "TAASSUP", "TAHARET", "TAHIYYE", "TAKIYYE", "TARİKAT", "TATAVVU", "TAZARRU",
    "TEFRİKA", "TELBİYE", "TENASÜH", "TENEŞİR", "TEOLOJİ", "TERBİYE", "TERCÜME", "TEVATÜR",
    "TEZKİYE", "TİLAVET", "TİRMİZİ", "TÛRDAĞI", "ULULEMR", "ULÜLEMR", "ÜÇAYLAR", "VAKFİYE",
    "VALLAHİ", "VASİYET", "VEKÂLET", "VELADET", "VELAYET", "VESVESE", "YALAVAÇ", "YECÜCVE",
    "ZARURET", "ZEYDİYE", "ZİLKADE", "ÂDKAVMİ"
];
