// A comprehensive list of Turkish Islamic-themed words for the game.
// This list enables fully offline gameplay.
export const tr_words: string[] = [
    // 4 Harfli Kelimeler
    "ABES", "ACEM", "ADAK", "ADAP", "ADEM", "ADİL", "AFET", "AFİF", "AFÜV", "AHAD", "AHİT", "AKİF",
    "AKIL", "AKİT", "AKLI", "AKRA", "ALEM", "ALİM", "ALİY", "AMEL", "AMİL", "ANKA", "ARAF", "ARİF",
    "ASIR", "ATEH", "AVAM", "AYET", "AYİN", "AYIP", "AYŞE", "AZAB", "AZAP", "AZAT", "AZİM", "AZİZ",
    "AŞAR", "AŞIR", "BAKİ", "BEDİ", "BEKA", "BELA", "BERR", "BEYT", "BİAT", "BİRR", "BUĞZ", "BÂRÎ",
    "BÜYÜ", "CAİZ", "CAMİ", "CENK", "CERH", "CEVA", "CEZA", "CUDİ", "CUMA", "CÜRM", "DEDE", "DEFN",
    "DİN", "DOST", "DUA", "ECEL", "ECİR", "EDEB", "EDEP", "EHAD", "ELÇİ", "EMAN", "EMİN", "EMİR",
    "ENAM", "EREN", "ESER", "ESMA", "ESRA", "EZAN", "EZEL", "FAKA", "FAKR", "FARZ", "FAİZ", "FECR",
    "FERA", "FETA", "FETH", "FEYZ", "FISK", "FUHŞ", "FÜCU", "GAFR", "GASP", "GAVS", "GAYB", "GAZA",
    "GAZİ", "GÜNÜ", "HACC", "HACI", "HAK", "HAMD", "HAMR", "HAMT", "HATA", "HAVF", "HAYÂ", "HAŞA",
    "HAŞR", "HEVA", "HEZL", "HIRS", "HIZ", "HİBE", "HİCR", "HİDA", "HİS", "HİZB", "HOCA", "HUDA",
    "HUHU", "HURİ", "HUSU", "HUŞU", "HÂDİ", "HIFZ", "HIKD", "HÜKM", "HÜSN", "ICAR", "İCAZ", "İCMA",
    "İÇKİ", "İFTA", "İĞVA", "İHTİ", "İHYA", "İKAB", "İKTA", "İLAH", "İLİM", "İLMİ", "İMAM", "İMAN",
    "İNAM", "İSAR", "İSRA", "KABE", "KADE", "KADI", "KAFİ", "KALP", "KAVİ", "KAZA", "KAZF", "KEŞF",
    "KUL", "KURU", "KÖLE", "KÜFR", "LAHN", "LAĞV", "LUT", "MAHV", "MARİ", "MAZI", "MEAL", "MENİ",
    "MESH", "MEST", "MEZİ", "MİHR", "MİNA", "MUİD", "MUİZ", "MUTİ", "NAAŞ", "NAAT", "NASS", "NEBİ",
    "NEHY", "NESH", "NEZR", "NOEL", "NUR", "ORUÇ", "PAPA", "RABB", "RADA", "RAHM", "RAFİ", "RAKK",
    "RAUF", "RAVİ", "RECA", "REY", "RIFK", "RIZA", "RİBA", "RİCS", "RİYA", "RÜKÛ", "RÜŞD", "RÜŞT",
    "SAAT", "SABİ", "SABR", "SAFA", "SAHU", "SAİT", "SALA", "SAVM", "SECD", "SEMA", "SEMİ", "SIDK",
    "SİKA", "SUFİ", "SULB", "SULH", "SURE", "SÛR", "ŞAKİ", "ŞARİ", "ŞART", "ŞAVT", "ŞERH", "ŞERİ",
    "ŞEYH", "ŞİRK", "ŞÛRA", "ŞÜKR", "TABU", "TUBA", "UMRE", "UZZA", "ÜMMİ", "VAAZ", "VAHY", "VAİZ",
    "VALİ", "VASİ", "VAZ", "VECD", "VEDA", "VEDİ", "VEFA", "VELİ", "VERA", "VİRD", "YAD", "YEİS",
    "YUŞA", "ZAPT", "ZAT", "ZEVK", "ZİKR", "ZİNA", "ZULM", "ZÜHT", "ÂBİT", "ÂDEM", "ÂDET", "ÂHİR",
    "ÂLEM", "ÂMİN", "ÇİLE",

    // 5 Harfli Kelimeler
    "ABDAL", "ABİDE", "ACEMÎ", "ADAVE", "ADNAN", "AĞACI", "AHBAR", "AHLAK", "AHKÂM", "AHYAR", "AKABE",
    "AKAİT", "AKİDE", "AKİKA", "ALAKA", "ALEVİ", "ALEYH", "ALLAH", "ÂMİL", "AREFE", "ARİFE", "ARRAF",
    "ASHAB", "ASRIN", "AŞURE", "AVRET", "AYLAR", "AZİZE", "BAHAİ", "BAHİR", "BALİĞ", "BASAR", "BASÎR",
    "BATIL", "BÂTIN", "BEKKE", "BELAM", "BERAT", "BEŞER", "BETÜL", "BEYAN", "BEŞİR", "BİDAT", "BİLGİ",
    "BİSET", "BUĞUZ", "BURAK", "BÜLUĞ", "CAHİL", "CAHİM", "CEDEL", "CELAL", "CELİL", "CEMAA", "CENİN",
    "CEVAP", "CEVAZ", "CEZBE", "CİDAL", "CİHAT", "CİMRİ", "CİZYE", "CÜBBE", "CÜLUS", "CÜNAH", "CÜNUN",
    "CÜNÜP", "CÜRÜM", "ÇALAP", "DAVET", "DAVUD", "DEFİN", "DEHRİ", "DELİL", "DEYİŞ", "DİDAR", "DİVAN",
    "DİYET", "DÜNYA", "EBCET", "EBDAL", "EBRAR", "EBTER", "ECRİN", "EFDAL", "EKREM", "ENFAL", "ENSAR",
    "ERVAH", "ESFEL", "EŞARÎ", "EVKAF", "EVLÂD", "EVRAD", "EVVEL", "EYVAL", "EZELÎ", "EZLAM", "FACİR",
    "FAHİŞ", "FAKİH", "FAKİR", "FÂNİ", "FASIK", "FASİT", "FECİR", "FELAH", "FESAD", "FESAT", "FESİH",
    "FETİH", "FETVA", "FEYİZ", "FIKIH", "FIRKA", "FITRA", "FİDYE", "FİİL", "FİTEN", "FİTNE", "FİTRE",
    "FUHUŞ", "FÜCUR", "GAFUR", "GALAT", "GARİP", "GASİL", "GAYBİ", "GAZAB", "GAZAP", "GAZVE", "GIPTA",
    "GIYAR", "GÖNLÜ", "GÖNÜL", "GURRE", "GUSÜL", "GÜNAH", "GÂVUR", "HABER", "HABİL", "HABİS", "HABÎR",
    "HADES", "HADİS", "HAFIZ", "HAFÎZ", "HÂFIZ", "HAHAM", "HAKEM", "HAKÎM", "HALİL", "HALÎM", "HÂLİK",
    "HAMÎD", "HANİF", "HARAÇ", "HARAM", "HAREM", "HASET", "HASİS", "HASÎB", "HAŞİR", "HATİM", "HATİP",
    "HATÎM", "HAVAS", "HAVLE", "HAVRA", "HAYAT", "HAYIR", "HAYIZ", "HİDAY", "HELAL", "HICAB", "HİCAP",
    "HİCAZ", "HİLAF", "HİLAL", "HİLİM", "HİLYE", "HİTAN", "HİYEL", "HİZİP", "HULUL", "HUMUS", "HUTBE",
    "HUZUR", "HZALİ", "HÂFID", "HÂKİM", "HÂLIK", "HIZIR", "HÜBEL", "HÜCCET", "HÜKÜM", "HÜLLE", "HÜNSA",
    "HÜSNA", "HÜSÜN", "ISKAT", "ISLAH", "İBAHA", "İBADET", "İBLİS", "İBRET", "İDDET", "İFADA", "İFFET",
    "İFLAS", "İFRAT", "İFRİT", "İFSAT", "İFTAR", "İHBAT", "İHLAS", "İHRAM", "İHSAN", "İHSAR", "İHVAN",
    "İKRAH", "İKRAR", "İLAH", "İLAHİ", "İLAHÎ", "İLHAM", "İLHAD", "İLLET", "İMAME", "İMARE", "İMSAK",
    "İNABE", "İNFAK", "İNKÂR", "İNSAN", "İNZAL", "İNZAR", "İRADE", "İRFAN", "İRHAS", "İRŞAT", "İSMET",
    "İSNAT", "İSRAF", "İSTİH", "İTAAT", "İTLAF", "İYAFE", "İZZET", "KABİL", "KABİR", "KADER", "KADİR",
    "KAMET", "KARUN", "KASEM", "KAVİM", "KÂBID", "KÂFİR", "KÂHİN", "KEBİR", "KEFEN", "KEFİL", "KELAM",
    "KELİM", "KERİM", "KEŞİŞ", "KIBİR", "KIBLE", "KIDEM", "KISAS", "KISSA", "KİBİR", "KISVE", "KIYAM",
    "KIYAS", "KİTAB", "KİTAP", "KUDÜS", "KULAK", "KUMAR", "KUNUT", "KURAN", "KURRA", "KUTUB", "KUTUP",
    "KÜFRE", "KÜFRÜ", "KÜFÜR", "KÜFÜV", "KÜRSİ", "KÜRSÜ", "LAKAP", "LANET", "LATİF", "LİSAN", "LÜTUF",
    "MABED", "MABET", "MABUD", "MABUT", "MACİD", "MAHYA", "MAKAM", "MALİK", "MARUF", "MARUT", "MASUM",
    "MAŞER", "MATUH", "MAZUR", "MECİD", "MECÜC", "MEHDİ", "MEHİR", "MEKKE", "MELEK", "MELİK", "MELUN",
    "MEMNU", "MENAT", "MERVE", "MESİH", "METAF", "METİN", "MEVLA", "MEVLİ", "MEYTE", "MEZAR", "MEŞRU",
    "MİKAT", "MİRAC", "MİRAÇ", "MİRAS", "MİSAK", "MİZAN", "MOLLA", "MUBAH", "MUHSİ", "MUKİM", "MUKİT",
    "MUĞNİ", "MUSKA", "MÜBDİ", "MÜFTÜ", "MÜLGA", "MÜMİN", "MÜMİT", "MÜNŞİ", "MÜRİT", "MÜZİL", "NAMAZ",
    "NAMUS", "NASİH", "NAZAR", "NECEŞ", "NEFES", "NEFİS", "NEFSİ", "NEHİY", "NESAİ", "NESEB", "NESEP",
    "NEZİR", "NİFAK", "NİFAS", "NİKÂH", "NİMET", "NİSA", "NİSAP", "NİYET", "NURAN", "OLMAK", "PAGAN",
    "PAPAZ", "RABBE", "RAHİM", "RAHİP", "RAHLE", "RAKIB", "RAKIM", "RAŞİT", "RECEP", "RECİM", "REHİN",
    "REKÂT", "REMEL", "RESUL", "REŞİD", "REŞİT", "RIHLE", "RIZIK", "RIZKI", "RİBAT", "RİKAZ", "RUKYE",
    "RÜKÜN", "RÜZGÂR", "SABIR", "SABİİ", "SABUR", "SADAK", "SADAT", "SADIK", "SAHUR", "SALAT", "SALİH",
    "SALİK", "SALİP", "SAMED", "SARIK", "SEBİL", "SECCA", "SECDE", "SEFER", "SEFİH", "SEHER", "SELAM",
    "SELEM", "SENET", "SEVAB", "SEVAP", "SEYİT", "SIDIK", "SİHİR", "SİYER", "SUHUF", "SUNUŞ", "SÛRET",
    "SÜCUD", "SÜNEN", "SÜNNİ", "SÜTRE", "ŞABAN", "ŞABAT", "ŞAFİİ", "ŞAHİT", "ŞAHİD", "ŞAMAN", "ŞEHİD",
    "ŞEHİT", "ŞEKER", "ŞEKÛR", "ŞERİF", "ŞERİK", "ŞÜKÜR", "TÂBİ", "TABUT", "TADİL", "TAĞUT", "TAKKE",
    "TAKVA", "TALAK", "TALEB", "TANAH", "TASAV", "TAVAF", "TAZİM", "TAZİR", "TEALA", "TEFRİ", "TEKKE",
    "TEVİL", "TUFAN", "TÖVBE", "TÜRBE", "ULVÎ", "UZLET", "ÜLFET", "ÜMMET", "VACİP", "VAHİD", "VAHİY",
    "VAHYİ", "VAKAR", "VAKFE", "VAKIF", "VAKİT", "VAKTİ", "VATAN", "VEBAL", "VECH", "VEDİA", "VEDÛD",
    "VEKİL", "VELED", "VİTİR", "VÂKIF", "VÂRİS", "VÜCUH", "VÜCUT", "YAHYA", "YAKIN", "YAKÎN", "YALAN",
    "YASA", "YEMİN", "YETİM", "YOBAZ", "YORTU", "ZAHİR", "ZAHİT", "ZAKİR", "ZALİM", "ZEBUR", "ZEKÂT",
    "ZEKER", "ZELLE", "ZIHAR", "ZİKİR", "ZİKRİ", "ZİMMİ", "ZULÜM", "ZÜHRE",

    // 6 Harfli Kelimeler
    "ABDEST", "ADALET", "ADAVET", "ÂDEMİY", "AFOROZ", "AFİYET", "AHADİS", "AHİLİK", "AHİRET",
    "AHMEDÖ", "AKİDET", "AKRABA", "ALAMET", "AMENNA", "AMENTÜ", "ARAFAT", "ARASAT", "ATEİST",
    "ATEİZM", "AZAZİL", "AZİMET", "AZRAİL", "BAHTİY", "BAYRAM", "BEDDUA", "BELAGAT", "BELKIS",
    "BERZAH", "BESMELE", "BİLLAH", "BUDİZM", "BUHARİ", "BURHAN", "BÜHTAN", "CAFERÎ", "CARİYE",
    "CEBBAR", "CEHENNEM", "CEMAAT", "CENAZE", "CENNET", "CİBRİL", "CÖMERT", "CUMHUR", "ÇARMIH",
    "ÇELEBİ", "DAİMA", "DECCAL", "DERGÂH", "DERVİŞ", "DESTUR", "DİNDAR", "DİRHEM", "DİYANET",
    "EBABİL", "EBCED", "EFENDİ", "EHLİBEYT", "EHLİSA", "ELMÂNİ", "EMANET", "EMANETİ", "ENBİYA",
    "ERBAİN", "ESATİR", "ESMAYI", "ESRAR", "EVLİYA", "EYYÜB", "FARİZA", "FASILA", "FATIMA", "FÂTİHA",
    "FERAİZ", "FETTAH", "FITRAT", "FİRAVUN", "FUKAHA", "FUKARA", "FURKAN", "GAFFAR", "GAFLET",
    "GALİYE", "GASİLİ", "GASSAL", "GECESİ", "GILMAN", "GIYBET", "GUFRAN", "GURBET", "HÂDİMİ",
    "HAFİYYE", "HAKDİN", "HAKKANI", "HALİFE", "HALİME", "HALVET", "HAMAİL", "HANBELİ", "HANEFİ",
    "HANKÂH", "HANNÂN", "HARUN", "HASENE", "HAŞİMİ", "HAŞİYE", "HAŞYET", "HATMİŞERİF", "HAVARİ",
    "HAVİYE", "HAYRAT", "HAZRET", "HEYBET", "HICABE", "HİCRAN", "HİCRET", "HİDÂYET", "HİDANE",
    "HİKMET", "HİMMET", "HUDARÎ", "HURAFE", "HUTAME", "HIZLAN", "HZMUSA", "HZÖMER", "HÜCCET",
    "HÜNKÂR", "HÜRMÜZ", "HÜSRAN", "HÜTHÜT", "IKERİM", "IZTIBA", "İBADET", "İCABET", "İCAZET",
    "İFTİRA", "İHANET", "İHTİDA", "İKİNDİ", "İLÂHİYAT", "İKAMET", "İKTİDA", "İMAMET", "İMANLI",
    "İNANÇ", "İNAYET", "İNCİL", "İSEVİ", "İSLAM", "İSRAİL", "İSTİLA", "İSTİVA", "İTİDAL",
    "İTİKAT", "İTİKÂF", "İTTİKA", "KADİRİ", "KAHHAR", "KANAAT", "KAVİYYEN", "KAYYUM", "KEBİRE",
    "KEFAET", "KERAMET", "KEVSER", "KILİSE", "KIRAAT", "KİFAYET", "KİSÂBÎ", "KİTABİ", "KUDDÛS",
    "KUDDUS", "KUDRET", "KURBAN", "LOKMAN", "MAAZAL", "MAHCUR", "MAHFİL", "MAHREM", "MAHŞER",
    "MAKBER", "MAKBUL", "MALİKİ", "MASİVA", "MASUME", "MAUNET", "MECUSİ", "MECZUP", "MEDİNE",
    "MEDYEN", "MEGAZİ", "MEKRUH", "MELEKE", "MENDUP", "MENNAN", "MENSUH", "MERHUM", "MESBUK",
    "MESCİD", "MESCİT", "MESRUR", "MEVİZE", "MEVLİD", "MEYSİR", "MEZHEP", "MEZMUR", "MİHRAP",
    "MİKAİL", "MİLLET", "MİNARE", "MİNBER", "MİNHAC", "MİSKİN", "MİSVAK", "MUAHAT", "MUCİZE",
    "MÜCAHİT", "MUHLİS", "MUHRİM", "MUHSAN", "MUHSAR", "MUHSİN", "MUKSİT", "MURDAR", "MUSEVİ",
    "MUSHAF", "MÜDRİK", "MÜFLİS", "MÜFSİT", "MÜKREH", "MÜLHİT", "MÜNKER", "MÜNKİR", "MÜRCİE",
    "MÜRTET", "MÜRŞİD", "MÜRŞİT", "MÜSKİR", "MÜSLİM", "MÜSNET", "MÜSRİF", "MÜSTECAB", "MÜŞFİK",
    "MÜTREF", "MÜŞRİK", "NAFAKA", "NAFİLE", "NAMAZI", "NANKÖR", "NASARA", "NEMİME", "NEMRUT",
    "NEZAİR", "NÜBÜVVET", "ONEMİR", "PATRİK", "RABITA", "RAFIZİ", "RAHİBE", "RAHMAN", "RAHMET",
    "RAHMETİ", "RAKABE", "REFREF", "REYYAN", "REZZAK", "RIDVAN", "RIHLET", "RIZVAN", "RİDDET",
    "RİFADE", "RUHBAN", "RUHANİ", "RUHSAT", "RÜŞVET", "RÜVVET", "SABİHA", "SADAKA", "SÂDİKA",
    "SAHABE", "SÂLİHA", "SAMİRİ", "SEBÎLİ", "SEFERİ", "SELÂMET", "SEYYİE", "SIDDIK", "SİCCİN",
    "SİKAYE", "SİDRE", "SÜBHAN", "SÜNNET", "ŞECAAT", "ŞEFAAT", "ŞEFİKA", "ŞEHİDET", "ŞEREFE",
    "ŞERİAT", "ŞEVVAL", "ŞEHVET", "ŞEYTAN", "ŞİİLİK", "ŞÜHEDA", "TÂHİRE", "TABİİN", "TAHRİF",
    "TAKDİR", "TAKDİS", "TAKLİT", "TALMUT", "TASAVVUF", "TASDİK", "TAYYİB", "TAZİMİ", "TAZİYE",
    "TEBLİĞ", "TEBZİR", "TECVİT", "TEDVİN", "TEENNİ", "TEFEKKÜR", "TEFSİR", "TEHLİL", "TEKBİR",
    "TEKBÎR", "TEÇHİZ", "TEKFİN", "TEKFİR", "TEKVİN", "TELFİK", "TELKİN", "TEMYİZ", "TENZİH",
    "TENZİL", "TEREKE", "TERTİL", "TESBİH", "TESLİS", "TESPİH", "TEVESSÜL", "TEVAZU", "TEVFİK",
    "TEVHİT", "TEVRAT", "TUĞYAN", "TÜCCAR", "TÜVVET", "UBUDİYET", "UHREVİ", "UKUBAT", "ULVİYYE",
    "ÜZEYİR", "VAFTİZ", "VECİBE", "VEDİZM", "VEHHAB", "VELİME", "VESİLE", "VESVESE", "VİCDAN",
    "VUSLAT", "YESRİB", "YÛNUS", "ZAKKUM", "ZAVİYE", "ZEBANİ", "ZEKERİYA", "ZEMZEM", "ZIMMET",
    "ZINDIK", "ZİYADÖ", "ZÜLFİK", "ZÜNNAR", "ZÜNNUN", "ÂLİABA",

    // 7 Harfli Kelimeler
    "ABADİLE", "ABDİYET", "ADAVETİ", "AKŞAMNA", "ÂHİRETİ", "ÂLEMLER", "ÂLEMLERE", "ALPEREN",
    "ASİTANE", "BABİLİK", "BASİRET", "BAYRAMI", "BEKTAŞİ", "BELAGAT", "BEREKET", "BEREKETİ",
    "BESMELE", "BEYYİNE", "BİLLAHİ", "BOŞANMA", "CEBRAİL", "CEBRİYE", "CEHENNEM", "CEHENNEMİ",
    "CENABET", "DALALET", "DEHRİYE", "DİLENCİ", "DİNGÜNÜ", "DİYANET", "DİYANETİ", "EBEVEYN",
    "EHLİBEYT", "EHLİHAK", "EHLİHÂL", "EHLİREY", "EHLİYET", "EHRİMEN", "ELGAFUR", "EMÂNETİN",
    "EMANETE", "EMRİBİL", "EMRİHAK", "FÂTİMATÜZ", "FAZİLET", "FELSEFE", "FERASET", "FERİŞTEH",
    "FETANET", "FİRASET", "FİRAVUN", "FİRDEVS", "GAFLETİ", "GANİMET", "HAKİKAT", "HALETME",
    "HÂMİDİNE", "HAMDELE", "HAMETİM", "HAMİYET", "HANBELİ", "HASENAT", "HAVATIR", "HAVKALE",
    "HERVELE", "HİDÂYETİ", "HIDAYET", "HİLAFET", "HİTABET", "HIYANET", "HURAFAT", "HUSUMET",
    "HÜSNÜZAN", "HZHASAN", "HZHAVVA", "HZOSMAN", "HZÂMİNE", "İBADETİN", "İBRANİ", "İÇTİHAD",
    "İÇTİHAT", "İHTİKAR", "İHTİLAF", "İHTİLAM", "İHTİLAT", "İHTİYAT", "İKTİBAS", "İKTİSAT",
    "İLMİHÂL", "İMAMEYN", "İNTİHAR", "İNTİSAP", "İRTİDAT", "İSRAİL", "İSTİANE", "İSTİAZE",
    "İSTİBRA", "İSTİĞFAR", "İSTİHZA", "İSTİLAM", "İSTİNCA", "İSTİRCÂ", "İSTİSKA", "İZDİVAÇ",
    "ISTILAM", "KABİLİYET", "KADERİYE", "KADİRİYE", "KATOLİK", "KEFALET", "KEFARET", "KEFFARET",
    "KEHANET", "KEMAYET", "KERAHET", "KERAMET", "KERÂMETİ", "KISASEN", "KIYAMET", "LAHAVLE",
    "LEBBEYK", "MAĞFİRET", "MAKBULİYET", "MARİFET", "MASİYET", "MAZMAZA", "MECELLE", "MEDRESE",
    "MELEKÛT", "MENASİK", "MENKIBE", "MERHABA", "MERYEMANA", "MESNEVİ", "MESTURE", "MEVHİBE",
    "MEZHEBİ", "MİSAFİR", "MUHACİR", "MUHAMMED", "MUKTEDİ", "MUSALLA", "MUSALLİ", "MUTTAKİ",
    "MUVATTA", "MÜBAHALE", "MÜBAREK", "MÜCAHİT", "MÜEZZİN", "MÜHTEDİ", "MÜNACAT", "MÜNAFIK",
    "MÜRAHİK", "MÜRTECİ", "MÜSLÜMAN", "NASİHAT", "NASRANİ", "NECASET", "NEZAFET", "NEZAHET",
    "ÖRTÜNME", "RABBANİ", "RAHMANİYE", "RAHMETİN", "RAMAZAN", "RAVZAYI", "RESÛLULLAH", "RİSALET",
    "RİVAYET", "RİYAKÂR", "RİYAZET", "SAADETİ", "SADAKAT", "SÂDÂKATİ", "SAHİHAN", "SALVELE",
    "SECCADE", "SECDESİ", "SELÂMETİ", "SERİYYE", "SİNAGOG", "SÜLEYMAN", "ŞEHADET", "ŞEFAATİ",
    "ŞERİATI", "ŞEYHAYN", "TAASSUB", "TAASSUP", "TAHARET", "TAHIYYE", "TAHMİDEN", "TAKIYYE",
    "TAKDİSEN", "TARİKAT", "TATAVVU", "TAZARRU", "TEFRİKA", "TELBİYE", "TENASÜH", "TENEŞİR",
    "TEOLOJİ", "TERBİYE", "TERCÜME", "TEVATÜR", "TEVEKKÜL", "TEZKİYE", "TİLAVET", "TİRMİZİ",
    "TÛRDAĞI", "ULULEMR", "ULÜLEMR", "ÜÇAYLAR", "VAKFİYE", "VALLAHİ", "VASİYET", "VEKÂLET",
    "VELADET", "VELAYET", "VESVESE", "YALAVAÇ", "YECÜCVE", "ZARURET", "ZEKERİYYA", "ZEYDİYE",
    "ZİLKADE", "ÂDKAVMİ"
];